/**
 * X-WEB World Target — AR Engine Logic
 * ======================================
 * DO NOT EDIT THIS FILE for per-client customization.
 * All configuration is in config.js.
 *
 * This file handles:
 * - Launch screen population from config
 * - GPS geolocation and distance calculation
 * - GPS state machine (idle → approaching → in_range → playing)
 * - Three.js 3D model loading and rendering
 * - Camera feed background
 */

import * as THREE from "three";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";

// ─── STATE ──────────────────────────────────────────────────────

let gpsState = "idle"; // idle → approaching → in_range → playing
let watchId = null;
let scene, camera, renderer, model, controls;
let cameraStream = null;

// ─── INITIALIZATION ─────────────────────────────────────────────

document.addEventListener("DOMContentLoaded", () => {
  initLaunchScreen();
});

function initLaunchScreen() {
  const config = window.XWEB_CONFIG;
  if (!config) {
    console.error("[X-WEB] No XWEB_CONFIG found. Check config.js.");
    return;
  }

  document.getElementById("app-title").textContent = config.appName;
  document.getElementById("channel-name").textContent = config.channelName;
  document.getElementById("model-title").textContent = config.experience.title;
  document.getElementById("model-location").textContent = config.experience.location;

  // If radius is huge (testing mode), show bypass note
  if (config.gps.radius >= 999999) {
    document.getElementById("instructions-text").textContent =
      "GPS bypass enabled (testing mode). Tap to launch directly.";
  }
}

// ─── GPS ────────────────────────────────────────────────────────

window.startGPS = function() {
  const config = window.XWEB_CONFIG;
  const btn = document.getElementById("launch-btn");
  btn.textContent = "LOCATING...";
  btn.disabled = true;

  // If GPS bypass mode, go straight to camera
  if (config.gps.radius >= 999999) {
    transitionTo("in_range");
    return;
  }

  if (!navigator.geolocation) {
    btn.textContent = "GPS NOT AVAILABLE";
    return;
  }

  document.getElementById("location-info").style.display = "block";

  watchId = navigator.geolocation.watchPosition(
    (position) => {
      const dist = haversineDistance(
        position.coords.latitude,
        position.coords.longitude,
        config.gps.latitude,
        config.gps.longitude
      );

      updateDistance(dist);

      if (dist <= config.gps.radius && gpsState !== "in_range") {
        transitionTo("in_range");
      } else if (gpsState === "idle") {
        transitionTo("approaching");
      }
    },
    (err) => {
      console.error("[X-WEB] GPS error:", err);
      document.getElementById("distance-text").textContent = "GPS Error — Use Launch Camera button";
      transitionTo("approaching"); // Show bypass button
    },
    { enableHighAccuracy: true, maximumAge: 5000, timeout: 10000 }
  );
};

function transitionTo(newState) {
  // One-way latch: once in_range, never go back (prevents GPS jitter)
  if (gpsState === "in_range" && newState !== "playing") return;

  gpsState = newState;

  switch (newState) {
    case "approaching":
      document.getElementById("launch-screen").classList.remove("active");
      document.getElementById("approaching-screen").classList.add("active");
      break;

    case "in_range":
      // Clear GPS watch — we're done with it
      if (watchId) {
        navigator.geolocation.clearWatch(watchId);
        watchId = null;
      }
      // Auto-launch camera
      launchCamera();
      break;

    case "playing":
      break;
  }
}

function updateDistance(meters) {
  const distText = meters > 1000
    ? `${(meters / 1000).toFixed(1)} km away`
    : `${Math.round(meters)} m away`;

  document.getElementById("distance-text").textContent = distText;
  document.getElementById("approach-distance").textContent = distText;
}

function haversineDistance(lat1, lon1, lat2, lon2) {
  const R = 6371000; // Earth radius in meters
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
    Math.sin(dLon / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

// ─── CAMERA LAUNCH ──────────────────────────────────────────────

window.launchCamera = async function() {
  // Switch to camera screen
  document.getElementById("launch-screen").classList.remove("active");
  document.getElementById("approaching-screen").classList.remove("active");
  document.getElementById("camera-screen").classList.add("active");

  // Start camera feed
  try {
    cameraStream = await navigator.mediaDevices.getUserMedia({
      video: { facingMode: "environment", width: { ideal: 1920 }, height: { ideal: 1080 } }
    });
    const videoEl = document.getElementById("camera-feed");
    videoEl.srcObject = cameraStream;
    videoEl.style.display = "block";
    videoEl.style.position = "absolute";
    videoEl.style.inset = "0";
    videoEl.style.width = "100%";
    videoEl.style.height = "100%";
    videoEl.style.objectFit = "cover";
    videoEl.style.zIndex = "0";
    document.getElementById("ar-viewport").appendChild(videoEl);
  } catch (err) {
    console.warn("[X-WEB] Camera access denied, using black background");
  }

  // Initialize Three.js renderer
  initThreeJS();
  gpsState = "playing";
};

window.exitCamera = function() {
  // Stop camera
  if (cameraStream) {
    cameraStream.getTracks().forEach(t => t.stop());
    cameraStream = null;
  }

  // Clean up Three.js
  if (renderer) {
    renderer.dispose();
    renderer = null;
  }

  // Clear viewport
  const viewport = document.getElementById("ar-viewport");
  viewport.innerHTML = '<video id="camera-feed" autoplay playsinline style="display:none;"></video>';

  // Switch screens
  document.getElementById("camera-screen").classList.remove("active");
  document.getElementById("launch-screen").classList.add("active");

  // Reset
  gpsState = "idle";
  const btn = document.getElementById("launch-btn");
  btn.textContent = "LOCATE ME";
  btn.disabled = false;
};

// ─── THREE.JS RENDERER ──────────────────────────────────────────

function initThreeJS() {
  const config = window.XWEB_CONFIG;
  const viewport = document.getElementById("ar-viewport");
  const width = viewport.clientWidth;
  const height = viewport.clientHeight;

  // Scene
  scene = new THREE.Scene();
  if (config.renderer.showFog) {
    scene.fog = new THREE.Fog(config.renderer.backgroundColor, 12, 30);
  }

  // Camera
  camera = new THREE.PerspectiveCamera(40, width / height, 0.01, 1000);
  camera.position.set(0, config.renderer.cameraHeight, config.renderer.cameraDistance);
  camera.lookAt(0, 0.4, 0);

  // Renderer (transparent to show camera feed behind)
  renderer = new THREE.WebGLRenderer({ alpha: true, antialias: true });
  renderer.setSize(width, height);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 1.2;
  renderer.domElement.style.position = "absolute";
  renderer.domElement.style.inset = "0";
  renderer.domElement.style.zIndex = "1";
  viewport.appendChild(renderer.domElement);

  // Lighting
  const ambientLight = new THREE.AmbientLight(0xffffff, 0.4);
  scene.add(ambientLight);

  const dirLight = new THREE.DirectionalLight(0xffffff, 1.2);
  dirLight.position.set(5, 10, 7);
  dirLight.castShadow = true;
  scene.add(dirLight);

  const fillLight = new THREE.DirectionalLight(0x8888ff, 0.3);
  fillLight.position.set(-5, 3, -5);
  scene.add(fillLight);

  // Ground plane
  if (config.renderer.showGround) {
    const groundGeo = new THREE.PlaneGeometry(50, 50);
    const groundMat = new THREE.MeshStandardMaterial({
      color: 0x111118,
      roughness: 0.6,
      metalness: 0.4,
    });
    const ground = new THREE.Mesh(groundGeo, groundMat);
    ground.rotation.x = -Math.PI / 2;
    ground.position.y = -0.01;
    ground.receiveShadow = true;
    scene.add(ground);
  }

  // Grid
  if (config.renderer.showGrid) {
    const grid = new THREE.GridHelper(20, 40, 0xC9A84C, 0xC9A84C);
    grid.material.opacity = 0.15;
    grid.material.transparent = true;
    scene.add(grid);
  }

  // Orbit controls (touch to rotate model)
  controls = new OrbitControls(camera, renderer.domElement);
  controls.enableDamping = true;
  controls.dampingFactor = 0.05;
  controls.enableZoom = true;
  controls.enablePan = false;
  controls.target.set(0, 0.5, 0);

  // Load model
  if (config.model.url) {
    loadModel(config);
  } else {
    // No model URL — show placeholder
    const geo = new THREE.BoxGeometry(1, 1, 1);
    const mat = new THREE.MeshStandardMaterial({ color: 0xC9A84C, wireframe: true });
    const placeholder = new THREE.Mesh(geo, mat);
    placeholder.position.y = 0.5;
    scene.add(placeholder);
    console.warn("[X-WEB] No model URL configured. Showing placeholder.");
  }

  // Animation loop
  animate();

  // Handle resize
  window.addEventListener("resize", () => {
    const w = viewport.clientWidth;
    const h = viewport.clientHeight;
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
    renderer.setSize(w, h);
  });
}

function loadModel(config) {
  const loader = new GLTFLoader();

  loader.load(
    config.model.url,
    (gltf) => {
      model = gltf.scene;

      // Normalize model: center at origin, scale to unit box, then apply user scale
      const rawBox = new THREE.Box3().setFromObject(model);
      model.position.sub(rawBox.getCenter(new THREE.Vector3()));
      const maxDim = Math.max(...rawBox.getSize(new THREE.Vector3()).toArray());
      model.scale.setScalar((1 / maxDim) * config.model.scale);

      // Lift base to ground level (y=0)
      const scaledBox = new THREE.Box3().setFromObject(model);
      model.position.y -= scaledBox.min.y;

      // Apply rotation
      model.rotation.y = (config.model.rotationY * Math.PI) / 180;

      // Enable shadows
      model.traverse((child) => {
        if (child.isMesh) {
          child.castShadow = true;
          child.receiveShadow = true;
        }
      });

      scene.add(model);
      console.log("[X-WEB] Model loaded successfully");
    },
    (progress) => {
      const pct = progress.total > 0 ? Math.round((progress.loaded / progress.total) * 100) : 0;
      console.log(`[X-WEB] Loading model: ${pct}%`);
    },
    (error) => {
      console.error("[X-WEB] Model load error:", error);
    }
  );
}

function animate() {
  if (!renderer) return;
  requestAnimationFrame(animate);
  if (controls) controls.update();
  renderer.render(scene, camera);
}
