/**
 * X-WEB Comms AR — Engine Logic
 * ==============================
 * DO NOT EDIT THIS FILE for per-client customization.
 * All configuration is in config.js.
 *
 * This file handles:
 * - Password gate
 * - 8th Wall image target detection
 * - Twilio Client VoIP call initiation
 * - Call state management
 */

let twilioDevice = null;
let activeConnection = null;

// ─── INITIALIZATION ─────────────────────────────────────────────

document.addEventListener("DOMContentLoaded", () => {
  const config = window.XWEB_CONFIG;
  if (!config) return;

  document.getElementById("app-title").textContent = config.appName;
  document.getElementById("channel-name").textContent = config.channelName;
  document.getElementById("call-label").textContent = config.twilio.callLabel;

  // Listen for Enter key on password input
  document.getElementById("password-input").addEventListener("keydown", (e) => {
    if (e.key === "Enter") checkPassword();
  });
});

// ─── PASSWORD GATE ──────────────────────────────────────────────

window.checkPassword = function() {
  const config = window.XWEB_CONFIG;
  const input = document.getElementById("password-input").value;

  if (input === config.password) {
    document.getElementById("password-screen").classList.remove("active");
    document.getElementById("launch-screen").classList.add("active");
  } else {
    document.getElementById("password-error").style.display = "block";
    document.getElementById("password-input").value = "";
    setTimeout(() => {
      document.getElementById("password-error").style.display = "none";
    }, 3000);
  }
};

// ─── CAMERA LAUNCH ──────────────────────────────────────────────

window.launchCamera = function() {
  const btn = document.getElementById("launch-btn");
  btn.textContent = "INITIALIZING...";
  btn.disabled = true;

  setTimeout(() => {
    document.getElementById("launch-screen").classList.remove("active");
    document.getElementById("camera-screen").classList.add("active");
    initAR();
  }, 400);
};

window.exitCamera = function() {
  // Hang up if active
  if (activeConnection) {
    activeConnection.disconnect();
    activeConnection = null;
  }

  const scene = document.querySelector("a-scene");
  if (scene) scene.remove();

  document.getElementById("camera-screen").classList.remove("active");
  document.getElementById("launch-screen").classList.add("active");

  const btn = document.getElementById("launch-btn");
  btn.textContent = "OPEN CAMERA";
  btn.disabled = false;

  resetCallUI();
};

// ─── AR INITIALIZATION ──────────────────────────────────────────

async function initAR() {
  const config = window.XWEB_CONFIG;

  try {
    await waitForXR8();

    const XR8 = window.XR8;
    XR8.XrController.configure({
      imageTargetData: [config.target.targetData],
    });

    createScene(config);
  } catch (err) {
    console.error("[X-WEB COMMS] AR init error:", err);
  }
}

function waitForXR8() {
  return new Promise((resolve, reject) => {
    if (window.XR8) { resolve(); return; }
    window.addEventListener("xrloaded", () => resolve(), { once: true });
    setTimeout(() => reject(new Error("8th Wall engine failed to load")), 15000);
  });
}

function createScene(config) {
  const container = document.getElementById("ar-container");

  const sceneHTML = `
    <a-scene
      xrextras-loading
      xrextras-runtime-error
      renderer="colorManagement:true"
      xrweb="disableWorldTracking: ${config.options.disableWorldTracking}"
      embedded
    >
      <a-camera position="0 4 10" raycaster="objects: .cantap" cursor="fuse: false; rayOrigin: mouse;"></a-camera>
      <a-light type="ambient" intensity="1"></a-light>

      <xrextras-named-image-target name="${config.target.name}">
        <a-entity
          geometry="primitive: plane; height: 0.3; width: 0.3;"
          material="color: #C9A84C; opacity: 0.5; transparent: true"
        ></a-entity>
      </xrextras-named-image-target>
    </a-scene>
  `;

  container.innerHTML = sceneHTML;

  const scene = container.querySelector("a-scene");
  scene.addEventListener("loaded", () => {
    setupTargetListener(config);
  });
}

function setupTargetListener(config) {
  const targetEl = document.querySelector(
    `xrextras-named-image-target[name="${config.target.name}"]`
  );
  if (!targetEl) return;

  targetEl.addEventListener("xrimagefound", () => {
    console.log("[X-WEB COMMS] Target detected");
    updateStatus("detected");
    document.getElementById("call-ui").classList.remove("hidden");
    document.getElementById("viewfinder").style.display = "none";
    document.getElementById("scan-hint").style.display = "none";

    if (config.options.autoCall) {
      initiateCall();
    }
  });

  targetEl.addEventListener("xrimagelost", () => {
    // Don't hide call UI if call is active
    if (!activeConnection) {
      document.getElementById("call-ui").classList.add("hidden");
      document.getElementById("viewfinder").style.display = "block";
      document.getElementById("scan-hint").style.display = "block";
      updateStatus("scanning");
    }
  });
}

// ─── TWILIO VOIP ────────────────────────────────────────────────

window.initiateCall = async function() {
  const config = window.XWEB_CONFIG;

  document.getElementById("call-btn").style.display = "none";
  document.getElementById("call-status").textContent = "Connecting...";
  updateStatus("calling");

  try {
    // 1. Get Twilio token from server
    const response = await fetch(config.twilio.tokenEndpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ identity: "xweb-caller" }),
    });

    if (!response.ok) throw new Error("Token fetch failed");
    const data = await response.json();

    // 2. Initialize Twilio Device
    twilioDevice = new Twilio.Device(data.token, {
      codecPreferences: ["opus", "pcmu"],
      fakeLocalDTMF: true,
      enableRingingState: true,
    });

    twilioDevice.on("ready", () => {
      console.log("[X-WEB COMMS] Twilio device ready");
      makeCall(config);
    });

    twilioDevice.on("error", (err) => {
      console.error("[X-WEB COMMS] Twilio error:", err);
      document.getElementById("call-status").textContent = "Connection error";
      resetCallUI();
    });

    twilioDevice.on("disconnect", () => {
      console.log("[X-WEB COMMS] Call ended");
      document.getElementById("call-status").textContent = "Call ended";
      activeConnection = null;
      resetCallUI();
      updateStatus("detected");
    });

  } catch (err) {
    console.error("[X-WEB COMMS] Call init error:", err);
    document.getElementById("call-status").textContent = "Failed to connect";
    resetCallUI();
  }
};

function makeCall(config) {
  activeConnection = twilioDevice.connect({
    To: config.twilio.destination,
    CallerId: config.twilio.callerId,
  });

  activeConnection.on("ringing", () => {
    document.getElementById("call-status").textContent = "Ringing...";
  });

  activeConnection.on("accept", () => {
    document.getElementById("call-status").textContent = "Connected";
    document.getElementById("hangup-btn").style.display = "inline-flex";
    updateStatus("live");
  });
}

window.hangupCall = function() {
  if (activeConnection) {
    activeConnection.disconnect();
    activeConnection = null;
  }
  if (twilioDevice) {
    twilioDevice.destroy();
    twilioDevice = null;
  }
  resetCallUI();
  updateStatus("detected");
};

function resetCallUI() {
  setTimeout(() => {
    document.getElementById("call-btn").style.display = "inline-flex";
    document.getElementById("hangup-btn").style.display = "none";
  }, 2000);
}

// ─── UI STATUS ──────────────────────────────────────────────────

function updateStatus(state) {
  const statusEl = document.getElementById("ar-status");

  const states = {
    scanning: { dot: "scanning", label: "Scanning", color: "var(--xweb-gold-dim)" },
    detected: { dot: "scanning", label: "Target Found", color: "var(--xweb-gold)" },
    calling: { dot: "scanning", label: "Calling", color: "var(--xweb-gold)" },
    live: { dot: "live", label: "On Call", color: "var(--xweb-red-live)" },
  };

  const s = states[state] || states.scanning;
  statusEl.innerHTML = `
    <span class="xweb-status-dot ${s.dot}"></span>
    <span style="font-family:var(--font-display); font-size:9px; color:${s.color}; letter-spacing:0.1em; text-transform:uppercase; margin-left:6px;">${s.label}</span>
  `;
}
