/**
 * X-WEB Image Target — AR Engine Logic
 * ======================================
 * DO NOT EDIT THIS FILE for per-client customization.
 * All configuration is in config.js.
 *
 * This file handles:
 * - Launch screen population from config
 * - 8th Wall engine initialization
 * - A-Frame scene creation with image targets
 * - Video/audio playback on target detection
 * - UI state management (scanning → detected → playing)
 */

// ─── INITIALIZATION ─────────────────────────────────────────────

document.addEventListener("DOMContentLoaded", () => {
  initLaunchScreen();
});

function initLaunchScreen() {
  const config = window.XWEB_CONFIG;
  if (!config) {
    console.error("[X-WEB] No XWEB_CONFIG found. Check config.js.");
    return;
  }

  // Populate branding
  document.getElementById("app-title").textContent = config.appName;
  document.getElementById("channel-name").textContent = config.channelName;
  document.getElementById("footer-channel").textContent = config.channelName;
  document.getElementById("target-count").textContent =
    `${config.targets.length} TARGET${config.targets.length !== 1 ? "S" : ""} LOADED`;

  // Enable launch button only if targets exist
  const btn = document.getElementById("launch-btn");
  if (config.targets.length === 0) {
    btn.textContent = "NO TARGETS CONFIGURED";
    btn.disabled = true;
    btn.style.opacity = "0.4";
  }
}

// ─── CAMERA LAUNCH ──────────────────────────────────────────────

function launchCamera() {
  const btn = document.getElementById("launch-btn");
  btn.textContent = "INITIALIZING...";
  btn.disabled = true;

  // Switch screens
  setTimeout(() => {
    document.getElementById("launch-screen").classList.remove("active");
    document.getElementById("camera-screen").classList.add("active");
    initAR();
  }, 400);
}

function exitCamera() {
  // Clean up scene
  const scene = document.querySelector("a-scene");
  if (scene) scene.remove();

  // Stop any playing media
  document.querySelectorAll("video, audio").forEach(el => {
    el.pause();
    el.currentTime = 0;
  });

  // Switch screens
  document.getElementById("camera-screen").classList.remove("active");
  document.getElementById("launch-screen").classList.add("active");

  // Reset launch button
  const btn = document.getElementById("launch-btn");
  btn.textContent = "OPEN CAMERA";
  btn.disabled = false;
}

// ─── AR INITIALIZATION ──────────────────────────────────────────

async function initAR() {
  const config = window.XWEB_CONFIG;

  try {
    // Wait for XR8 to be ready
    await waitForXR8();

    const XR8 = window.XR8;
    const XRExtras = window.XRExtras;

    // Configure image targets
    const targetDataArray = config.targets.map(t => t.targetData);
    XR8.XrController.configure({
      imageTargetData: targetDataArray,
    });

    // Create the A-Frame scene
    createScene(config);

    updateStatus("scanning");
  } catch (err) {
    console.error("[X-WEB] AR init error:", err);
    updateStatus("error", err.message);
  }
}

function waitForXR8() {
  return new Promise((resolve, reject) => {
    if (window.XR8) {
      resolve();
      return;
    }
    window.addEventListener("xrloaded", () => resolve(), { once: true });
    // Timeout after 15 seconds
    setTimeout(() => reject(new Error("8th Wall engine failed to load")), 15000);
  });
}

// ─── SCENE CREATION ─────────────────────────────────────────────

function createScene(config) {
  const container = document.getElementById("ar-container");

  // Build assets HTML
  let assetsHTML = "";
  config.targets.forEach((target, i) => {
    if (target.contentType === "video") {
      assetsHTML += `
        <video
          id="media-${target.name}"
          src="${target.contentUrl}"
          preload="auto"
          ${config.options.videoLoop ? 'loop="true"' : ""}
          crossorigin="anonymous"
          playsinline
          webkit-playsinline
        ></video>`;
    } else if (target.contentType === "audio") {
      assetsHTML += `
        <audio
          id="media-${target.name}"
          src="${target.contentUrl}"
          preload="auto"
          crossorigin="anonymous"
        ></audio>`;
    }
  });

  // Build target entities HTML
  let entitiesHTML = "";
  config.targets.forEach((target) => {
    if (target.contentType === "video") {
      entitiesHTML += `
        <xrextras-named-image-target name="${target.name}">
          <a-entity
            xrextras-play-video="video: #media-${target.name}; thumb: #media-${target.name}; canstop: true"
            geometry="primitive: plane; height: 1; width: 0.75;"
          ></a-entity>
        </xrextras-named-image-target>`;
    } else if (target.contentType === "audio") {
      // For audio, show a visual indicator plane
      entitiesHTML += `
        <xrextras-named-image-target name="${target.name}">
          <a-entity
            geometry="primitive: plane; height: 0.3; width: 0.3;"
            material="color: #C9A84C; opacity: 0.6; transparent: true"
            position="0 0.5 0"
          ></a-entity>
        </xrextras-named-image-target>`;
    }
  });

  const sceneHTML = `
    <a-scene
      xrextras-gesture-detector
      xrextras-loading
      xrextras-runtime-error
      renderer="colorManagement:true"
      xrweb="disableWorldTracking: ${config.options.disableWorldTracking}"
      embedded
    >
      <a-assets>${assetsHTML}</a-assets>

      <a-camera
        position="0 4 10"
        raycaster="objects: .cantap"
        cursor="fuse: false; rayOrigin: mouse;"
      ></a-camera>
      <a-light type="directional" intensity="0.5" position="1 1 1"></a-light>
      <a-light type="ambient" intensity="1"></a-light>

      ${entitiesHTML}
    </a-scene>
  `;

  container.innerHTML = sceneHTML;

  // Listen for image target events
  const scene = container.querySelector("a-scene");
  scene.addEventListener("loaded", () => {
    setupTargetListeners(config);
  });
}

// ─── TARGET EVENT LISTENERS ─────────────────────────────────────

function setupTargetListeners(config) {
  config.targets.forEach((target) => {
    // Image found
    const targetEl = document.querySelector(
      `xrextras-named-image-target[name="${target.name}"]`
    );

    if (!targetEl) return;

    targetEl.addEventListener("xrimagefound", () => {
      console.log(`[X-WEB] Target found: ${target.name}`);
      updateStatus("detected");
      document.getElementById("footer-target").textContent = target.label;

      if (target.contentType === "video") {
        // Show tap-to-play (no autoplay on mobile)
        document.getElementById("tap-to-play").classList.remove("hidden");
        window.__activeTarget = target;
      } else if (target.contentType === "audio") {
        document.getElementById("tap-to-play").classList.remove("hidden");
        window.__activeTarget = target;
      }
    });

    targetEl.addEventListener("xrimagelost", () => {
      console.log(`[X-WEB] Target lost: ${target.name}`);
      document.getElementById("tap-to-play").classList.add("hidden");
      updateStatus("scanning");
    });
  });
}

// ─── PLAYBACK ───────────────────────────────────────────────────

function playContent() {
  const target = window.__activeTarget;
  if (!target) return;

  const mediaEl = document.getElementById(`media-${target.name}`);
  if (mediaEl) {
    mediaEl.play().then(() => {
      updateStatus("live");
      document.getElementById("tap-to-play").classList.add("hidden");
    }).catch(err => {
      console.error("[X-WEB] Playback error:", err);
    });
  }
}

// ─── UI STATUS ──────────────────────────────────────────────────

function updateStatus(state, errorMsg) {
  const statusEl = document.getElementById("ar-status");
  const viewfinder = document.getElementById("viewfinder");
  const scanHint = document.getElementById("scan-hint");

  switch (state) {
    case "scanning":
      statusEl.innerHTML = `
        <span class="xweb-status-dot scanning"></span>
        <span style="font-family:var(--font-display); font-size:9px; color:var(--xweb-gold-dim); letter-spacing:0.1em; text-transform:uppercase; margin-left:6px;">Scanning</span>
      `;
      viewfinder.classList.remove("hidden");
      scanHint.style.display = "block";
      break;

    case "detected":
      statusEl.innerHTML = `
        <span class="xweb-status-dot" style="background:var(--xweb-gold);"></span>
        <span style="font-family:var(--font-display); font-size:9px; color:var(--xweb-gold); letter-spacing:0.1em; text-transform:uppercase; margin-left:6px;">Detected</span>
      `;
      viewfinder.classList.add("hidden");
      scanHint.style.display = "none";
      break;

    case "live":
      statusEl.innerHTML = `
        <span class="xweb-status-dot live"></span>
        <span style="font-family:var(--font-display); font-size:9px; color:var(--xweb-red-live); letter-spacing:0.1em; text-transform:uppercase; margin-left:6px;">Live</span>
      `;
      viewfinder.classList.add("hidden");
      scanHint.style.display = "none";
      break;

    case "error":
      statusEl.innerHTML = `
        <span style="font-family:var(--font-display); font-size:9px; color:#EF4444; letter-spacing:0.1em; text-transform:uppercase;">Error: ${errorMsg || "Unknown"}</span>
      `;
      break;
  }
}
